### ISSUE TITLE
Questions regarding difference between pybullet and rustbullet

### ISSUE THREAD

**Issue by ghost** [neachdainn/rubullet#10]
Hello,

Sorry this problem may seem trivial to you. I came from control's background and works extensively with pybullet. Today I heard from one of my colleagues regarding this repo. I wonder if you may briefly elaborate the main advantage of rustbullet over pybullet? I think a lot of robotists would also be curious so this question may help them as well.

Many thanks in advance.

**Comment by neachdainn** [comment]
Mostly the language used to directly interact with the simulation. In PyBullet, it's Python. In RuBullet, it's Rust. Both of them use the C API to interface with the Bullet physics engine and RuBullet's API is designed to be *very* similar to PyBullet, so there is likely to not be much difference between the two beyond the programming language. An example of this is the implementation of [RuBullet's `Client::get_base_transform`][1] and [PyBullets's `getBasePositionAndOrientation`][2] - you should notice that, except for the Python argument shuffling, they are almost identical.

Beyond that, there are a few minor details. There are a few places I believe RuBullet checks for error conditions that PyBullet doesn't. RuBullet also uses actual algebraic types for vectors, quaternion, etc. whereas PyBullet just uses lists. Small stuff like that.

**EDIT:** Well, most of PyBullet's argument shuffling actually happens in [the wrapper function][3].

[1]: https://github.com/neachdainn/rubullet/blob/master/rubullet/src/client.rs#L602
[2]: https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/pybullet.c#L3928
[3]: https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/pybullet.c#L4074

**Comment by neachdainn** [comment]
Basically: If your code is in Python, use PyBullet. If it's in Rust, RuBullet is probably better.

**Comment by ghost** [comment]
Thank you.
